### ISSUE TITLE
s23u 国行被识别为了港版

### ISSUE THREAD

**Issue by Xuemq** [qlenlen/android_kernel_samsung_sm8550#10]
如题，是否因为我刷的soul官改？
![Screenshot_20240903_074343_Settings](https://github.com/user-attachments/assets/026ef5d4-b33c-4edd-9bee-fc946494c59f)

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by kalicyh** [comment]
目前在使用港版，指的是作者在使用港版设备，而不是指识别成港版设备吧

**Comment by Xuemq** [comment]
> 目前在使用港版，指的是作者在使用港版设备，而不是指识别成港版设备吧

懂了 😂😂😂
