### ISSUE TITLE
关于 vendor_dlkm 分区的驱动

### ISSUE THREAD

**Issue by BunnyYang05** [qlenlen/android_kernel_samsung_sm8550#12]
请问具体是修改了 vendor_dlkm 分区的哪些文件。
上次试着解包拿到你编译的驱动，移植到小23的时候，记得是 `max77705-fuelgauge.ko` 和 `sec-battery.ko`。
但刷了最新的内核和新做的 vendor_dlkm 镜像 ~~（原先正常能用的 img 被手贱删了）~~ 之后，
在 dmesg 里找不到 `sec_bat_get_temperature` 和 `Qmod`，只有 `sec_bat_get_battery_info` 和 `QMod`，觉得有点不对劲：
![Screenshot_20240904_031425_MT Manager](https://github.com/user-attachments/assets/9c8e5911-caee-4013-a505-ef88df08e7af)

**Comment by qlenlen** [comment]
因为`sec_bat_get_temperature`日志较多，比较冗余，所以人为取消输出了。

修改的地方是三处，第一是common内核温度读取，实际温度>=29以后减3.5°后再返回。第二处是lrp预估温度，它的值会始终与battery->temperature相同。第三处是max77705读取和写入的charger温度，设置恒定26°了。

驱动是sec-battery和max77705-fuelgauge两个，可以使用下方链接里的：
https://s-share.samsungcloudcn.com/cC2dquIXs9nx

另外，请问是Holatony老师吗，一直有这样的一种直觉

**Comment by BunnyYang05** [comment]
我不是哈哈哈哈哈，我是上次在酷安问你 super 打包刷不进去，还有第一次开机app闪退的那个
