### ISSUE TITLE
关于内核里hook_temp驱动

### ISSUE THREAD

**Issue by shiqixiaoyao** [qlenlen/android_kernel_samsung_sm8550#13]
对于内核中的hook_temp驱动，它对官方包仍然有效，非常希望作者大大能够继续更新这个驱动，以适配内核中的其他版本（因为其他版本我尝试刷入但失败了😭😭😭）。

**Comment by qlenlen** [comment]
我收到反馈是单独的hook_temp无法稳定亮屏快充，发热了依旧降频。只有dlkm替换驱动才能彻底生效，因此才停止更新hook_temp。

**Comment by shiqixiaoyao** [comment]
在同一环境下，使用无hook_temp驱动版本的设备在亮屏状态下充电时，充电功率仅为12w（而在息屏状态下，充电时间与官方描述一致，大约需要一个小时到一个半小时左右）。
hook_temp驱动版本在亮屏状态下充电速度大约能在20瓦左右（特别在息屏状态下，能在四十分钟内从6%充至100%）。
如果大大您觉得麻烦的话，能否单独开发一个模块，以模块化的方式来实现呢？

**Comment by BunnyYang05** [comment]
是S23吗？可以测试一下刷不带 hook_temp 的内核＋替换dlkm驱动之后的功率吗，自己没有设备😢

**Comment by BunnyYang05** [comment]
> 是S23吗？可以测试一下刷不带 hook_temp 的内核＋替换dlkm驱动之后的功率吗，自己没有设备😢

如果需要替换了驱动的镜像，我有适用S23最新港版的，fastbootd刷入：
https://s-share.samsungcloudcn.com/6x2XJFbe8gXY

**Comment by qlenlen** [comment]
> 在同一环境下，使用无hook_temp驱动版本的设备在亮屏状态下充电时，充电功率仅为12w（而在息屏状态下，充电时间与官方描述一致，大约需要一个小时到一个半小时左右）。
> hook_temp驱动版本在亮屏状态下充电速度大约能在20瓦左右（特别在息屏状态下，能在四十分钟内从6%充至100%）。
> 如果大大您觉得麻烦的话，能否单独开发一个模块，以模块化的方式来实现呢？

可以，这算是举手之劳。下次的内核发行版会附加一个模块

**Comment by shiqixiaoyao** [comment]
> > 是S23吗？可以测试一下刷不带 hook_temp 的内核＋替换dlkm驱动之后的功率吗，自己没有设备😢
> 
> 如果需要替换了驱动的镜像，我有适用S23最新港版的，fastbootd刷入：
> https://s-share.samsungcloudcn.com/6x2XJFbe8gXY

我是国行s23u系统能刷不

**Comment by shiqixiaoyao** [comment]
> > 在同一环境下，使用无hook_temp驱动版本的设备在亮屏状态下充电时，充电功率仅为12w（而在息屏状态下，充电时间与官方描述一致，大约需要一个小时到一个半小时左右）。
> > hook_temp驱动版本在亮屏状态下充电速度大约能在20瓦左右（特别在息屏状态下，能在四十分钟内从6%充至100%）。
> > 如果大大您觉得麻烦的话，能否单独开发一个模块，以模块化的方式来实现呢？
> 
> 可以，这算是举手之劳。下次的内核发行版会附加一个模块

谢谢大大

**Comment by BunnyYang05** [comment]
> > > 是S23吗？可以测试一下刷不带 hook_temp 的内核＋替换dlkm驱动之后的功率吗，自己没有设备😢
> > 
> > 
> > 如果需要替换了驱动的镜像，我有适用S23最新港版的，fastbootd刷入：
> > https://s-share.samsungcloudcn.com/6x2XJFbe8gXY
> 
> 我是国行s23u系统能刷不

不可以😂，但为什么ultra只有20W充电，不是45W的吗

**Comment by shiqixiaoyao** [comment]
> > > > 是S23吗？可以测试一下刷不带 hook_temp 的内核＋替换dlkm驱动之后的功率吗，自己没有设备😢
> > > 
> > > 
> > > 如果需要替换了驱动的镜像，我有适用S23最新港版的，fastbootd刷入：
> > > https://s-share.samsungcloudcn.com/6x2XJFbe8gXY
> > 
> > 我是国行s23u系统能刷不
> 
> 不可以😂，但为什么ultra只有20W充电，不是45W的吗

亮屏充电长稳20w已经很好了，你要是能刷q大快充第一版那个就六得一比直接拉满，但官包没解分区刷不进去要么刷进去开不起机

**Comment by shiqixiaoyao** [comment]
> > 在同一环境下，使用无hook_temp驱动版本的设备在亮屏状态下充电时，充电功率仅为12w（而在息屏状态下，充电时间与官方描述一致，大约需要一个小时到一个半小时左右）。
> > hook_temp驱动版本在亮屏状态下充电速度大约能在20瓦左右（特别在息屏状态下，能在四十分钟内从6%充至100%）。
> > 如果大大您觉得麻烦的话，能否单独开发一个模块，以模块化的方式来实现呢？
> 
> 可以，这算是举手之劳。下次的内核发行版会附加一个模块

Q大，模块做出来嘛？这两个最新的内核在亮屏充电时速度仅有十瓦，真的很难受😖。想要回退到老版本，但又想用新版本的功能。

**Comment by qlenlen** [comment]
> > > 在同一环境下，使用无hook_temp驱动版本的设备在亮屏状态下充电时，充电功率仅为12w（而在息屏状态下，充电时间与官方描述一致，大约需要一个小时到一个半小时左右）。
> > > hook_temp驱动版本在亮屏状态下充电速度大约能在20瓦左右（特别在息屏状态下，能在四十分钟内从6%充至100%）。
> > > 如果大大您觉得麻烦的话，能否单独开发一个模块，以模块化的方式来实现呢？
> > 
> > 可以，这算是举手之劳。下次的内核发行版会附加一个模块
> 
> Q大，模块做出来嘛？这两个最新的内核在亮屏充电时速度仅有十瓦，真的很难受😖。想要回退到老版本，但又想用新版本的功能。

今天晚点 补在ci0910

**Comment by shiqixiaoyao** [comment]
> > > > 在同一环境下，使用无hook_temp驱动版本的设备在亮屏状态下充电时，充电功率仅为12w（而在息屏状态下，充电时间与官方描述一致，大约需要一个小时到一个半小时左右）。
> > > > hook_temp驱动版本在亮屏状态下充电速度大约能在20瓦左右（特别在息屏状态下，能在四十分钟内从6%充至100%）。
> > > > 如果大大您觉得麻烦的话，能否单独开发一个模块，以模块化的方式来实现呢？
> > > 
> > > 可以，这算是举手之劳。下次的内核发行版会附加一个模块
> > 
> > Q大，模块做出来嘛？这两个最新的内核在亮屏充电时速度仅有十瓦，真的很难受😖。想要回退到老版本，但又想用新版本的功能。
> 
> 今天晚点 补在ci0910

好滴q大大
