### ISSUE TITLE
请问是否可以将One Box的各项功能进行整合？
另外，随着气温的下降，能否在加载hook_temp内核驱动时，增加一个狂暴模式，并设定温度判定阈值为26度（锁定此温度）？

### ISSUE THREAD

**Issue by shiqixiaoyao** [qlenlen/android_kernel_samsung_sm8550#18]
![Screenshot_20240923_115323_One Box.jpg](https://github.com/user-attachments/assets/3411eda2-03a5-437f-99e5-2158999fa855)

**Comment by qlenlen** [comment]
csc相关的，有计划加入

hook_temp的实现方式注定了它的局限性，要稳定解除温控只有dlkm能做到。将26.1改为26不会带来任何区别

另，阶梯式控温的dlkm，有计划集成在6.1.1新官改内(国行底包)

**Comment by shiqixiaoyao** [comment]
> csc相关的，有计划加入
> 
> hook_temp的实现方式注定了它的局限性，要稳定解除温控只有dlkm能做到。将26.1改为26不会带来任何区别
> 
> 另，阶梯式控温的dlkm，有计划集成在6.1.1新官改内(国行底包)

期待，但6.1.1不知什么时候才出来
