### ISSUE TITLE
Request for Kernel Source Code

### ISSUE THREAD

**Issue by mio-19** [qlenlen/android_kernel_samsung_sm8550#20]
I noticed that the kernel binary has been provided, but I couldn’t find the source code. Since the linux kernel is licensed under the GPL license, it’s required to share the source code along with the binary.
Could you please upload the kernel source or point me to where it’s available?

**Comment by qlenlen** [comment]
Thanks for your reminding. In order to comply with GPL, l will make this repo readonly and stop providing the kernel binary.
