### ISSUE TITLE
重启后失效（短信验证码。240hz采样率。刷新率）

### ISSUE THREAD

**Issue by nowhysss** [qlenlen/android_kernel_samsung_sm8550#25]
机型：S23U
系统：6.1.1最新
版本：[OneDesign_2.1.0.apk]

问题：以下功能重启后需要手动关开一次才能生效
1. 自动复制短信验证码
2. 采样率240hz
3. 刷新率120hz

感谢大佬，有空可以看下

**Comment by qlenlen** [comment]
检查内置存储有没有.bootreceiver文件
刷新率与采样率都是配置了自动任务的，会有日志。
短信，除非是读取信息的权限被系统/手动撤销了，不然不会失效的

**Comment by nowhysss** [comment]
> 检查内置存储有没有.bootreceiver文件 刷新率与采样率都是配置了自动任务的，会有日志。 短信，除非是读取信息的权限被系统/手动撤销了，不然不会失效的

好的感谢，解决了。重新用magisk给了下root权限重启了下就OK了
