### ISSUE TITLE
关闭所有SSRM相关设置，没有电池使用数据

### ISSUE THREAD

**Issue by nowhysss** [qlenlen/android_kernel_samsung_sm8550#26]
机型：s23u
版本：6.1.1
OneDesign版本：2.1.0

问题：关闭所有SSRM相关设置，用了一两天也重启过没有电池使用数据

**Comment by qlenlen** [comment]
将会检查hook条件判断，
另外，
如果不需要ssrm相关功能可以在lsp作用域里取消对device health的勾选

**Comment by qlenlen** [comment]
solved
