### ISSUE TITLE
OD 状态栏新功能bug

### ISSUE THREAD

**Issue by BunnyYang05** [qlenlen/android_kernel_samsung_sm8550#28]
调整状态栏日期文字大小的功能只在QyzROM可用，但是在其他ROM实际上也生效了，导致文字比默认的小。
![1000009873](https://github.com/user-attachments/assets/8ed75c7e-0a3b-47ba-8c78-de30c184e762)

**Comment by BunnyYang05** [comment]
原本应该是这个大小：
![1000009875](https://github.com/user-attachments/assets/335714cd-fc16-4c6f-a8b4-a85d708091f7)

**Comment by qlenlen** [comment]
oh默认值搞错了 （官方是15f的应该
