### ISSUE TITLE
Good Guardians 插件 Thermal Guardian 大范围失效

### ISSUE THREAD

**Issue by nowhysss** [qlenlen/android_kernel_samsung_sm8550#29]
机型：S23U
系统：6.1.1最新
版本：[OneDesign_2.1.0.apk]

问题：
1. 设备温度整个插件没有相关数据
2. 阈值温度无法调节
3. 更多设置的去严格选项必须留一个，全部取消就会重新勾选所有

![Screenshot_20241103_115444_Thermal Guardian](https://github.com/user-attachments/assets/85c4dee3-b2ff-439d-8f44-4afbb914a850)

**Comment by qlenlen** [comment]
更新至2.5，清空一次od数据并重启，如无意外可恢复

**Comment by nowhysss** [comment]
> 更新至2.5，清空一次od数据并重启，如无意外可恢复

没有恢复。应该在哪里清空一下？单独在设置里清空好像更奇怪了，明明托管关机菜单置灰的但是也有生效。还有电量数据依旧不显示。卸载重装也是。

**Comment by qlenlen** [comment]
2.5.1的od默认不对温控（ssrm）做任何修改
另外，提供的官方温控关闭界面：如果使用了官方的关闭温控选项，thermal guardian自然也会失效
