### ISSUE TITLE
关于手机区域判定

### ISSUE THREAD

**Issue by kalicyh** [qlenlen/android_kernel_samsung_sm8550#30]
我的手机是韩版的
用的soul系统会被判定成国行
能否增加一个选项开启港版专区

**Comment by qlenlen** [comment]
这个隐藏功能其实挺早就有了，长按onedesign标题可以唤出

本地化功能是对应版本的，od内的港版专区是对着xh2做适配的，更新的rom很可能会有不适配的情况，这些不可用暂不处理

**Comment by kalicyh** [comment]
噢噢，主要还是想试试onedrive的那个功能哈哈哈，然后我这边是灰色禁用的🫠

**Comment by qlenlen** [comment]
> 噢噢，主要还是想试试onedrive的那个功能哈哈哈，然后我这边是灰色禁用的🫠

onedrive自2.5.1 hook功能进一步完善，已经收编给qyz专用了
