### ISSUE TITLE
配置初始化失败

### ISSUE THREAD

**Issue by alexyuetmout** [qlenlen/android_kernel_samsung_sm8550#31]
![Screenshot_20241123_235518_Shell](https://github.com/user-attachments/assets/71a24643-6ad7-448f-aa0a-58aaaf483c61)
![Screenshot_20241123_235507](https://github.com/user-attachments/assets/88496dec-82d2-42aa-8ed3-6dc147de6cbf)
大佬我用2.5 2.6 2.61版本都会配置初始化失败，说lsp过旧，官方的1.92我系统xh7用不了了，用的修改版，该怎么办嘛

**Comment by qlenlen** [comment]
确保lsp作用域里勾选了OneDesign

**Comment by alexyuetmout** [comment]
![Screenshot_20241127_175611_Shell](https://github.com/user-attachments/assets/3261b31f-c93d-497b-bb84-5ef8b677230b)
![Screenshot_20241127_175558_Shell](https://github.com/user-attachments/assets/85218a51-3937-40d0-9fe8-ff8eacb8fddc)
都有选的，就跟其他用法一样用的，还是说有版本限制么。

**Comment by alexyuetmout** [comment]
![Screenshot_20241127_175946_OneDesign](https://github.com/user-attachments/assets/e753e422-b1cb-418d-a2c8-e6cae500cd1c)

**Comment by qlenlen** [comment]
没有版本限制，也没啥特别操作。安装后lsp激活就能使用。我也不清楚你的lsp出了什么问题

**Comment by alexyuetmout** [comment]
大佬这边用的lsp什么版本么，因为我用的是1.93mod，跟这个有关系么。因为原版的1。92不能用了，我是s24.
