### ISSUE TITLE
和knoxpatch模块冲突吗

### ISSUE THREAD

**Issue by iBye2mass** [qlenlen/android_kernel_samsung_sm8550#33]

**Comment by iBye2mass** [comment]
![Screenshot_20241201_024104_Shell](https://github.com/user-attachments/assets/77da9e42-8179-4acb-ba3f-aed678a500b0)
还有这个日志这个正常吗

**Comment by qlenlen** [comment]
od的knox修复只针对oneui6.1，比knoxpatch更轻量(是它的子集)

日志里配置项出了问题，其他app没法读取prefs，会导致选项修改后不生效。另外，你使用的版本可能比较旧了。新版才有knox修复功能

**Comment by iBye2mass** [comment]
感谢！
