### ISSUE TITLE
hook电话后后台压不住

### ISSUE THREAD

**Issue by iBye2mass1** [qlenlen/android_kernel_samsung_sm8550#37]
![Uploading Screenshot_20241228_200330.jpg…]()

**Comment by qlenlen** [comment]
电话作为系统级app本就是后台运行的，谈何压不压的住

**Comment by iBye2mass1** [comment]
hook电话app后台cpu占用一直在20%-30%

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
