### ISSUE TITLE
三星s23u 韩版刷入 CI_24.08.23+ 不开机

### ISSUE THREAD

**Issue by kalicyh** [qlenlen/android_kernel_samsung_sm8550#6]
sm s918n
soul系统
刷入 CI_24.08.23+ 不开机

还有老哥酷安怎么注销了

**Comment by baimablog** [comment]
> sm s918n soul系统 刷入 CI_24.08.23+ 不开机
> 
> 还有老哥酷安怎么注销了

你用soul出问题问啥。自己琢磨啊，，，我刷砖后来发现是自己操作错。不要啥问题都怪这个。。。为啥注销大概也是因为这个?

**Comment by kalicyh** [comment]
我用soul自带的更换kernelsu方式就成功了
