### ISSUE TITLE
OneDesign 功能请求

### ISSUE THREAD

**Issue by BunnyYang05** [qlenlen/android_kernel_samsung_sm8550#7]
### 相册（需要移植国行`priv-app/SamsungGalleryPlugins`）：
使`com/samsung/android/gallery/support/utils/Features`中的`IS_CHINA_DEVICE`始终为 true，从而调用高德地图，避免照片定位漂移，同时显示更准确的地点名称。
我的方法是修改`com/samsung/android/gallery/support/utils/Features$96`中的`getEnabling()`方法；以前尝试过只改`com/samsung/android/gallery/app/ui/map/factory/GalleryMapFactory`，但地点名称和地图预览又不正常，只好全局都改了。
### 短信（需要移植国行`app/SamsungMessages_Extension_Chn`）：
使信息 App 像国行一样支持分类对话和服务信息、黄页功能（装了黄页 App，不清楚是不是必需）、短信卡片化。
使`com.samsung.android.messaging.common.configuration.Feature`中`isChinaModel`方法返回 true 即可实现。

**以上功能直接改 apk 都可以成功实现，感觉直接 hook 会更方便，可是自己不会写 Xposed 模块😭**

### 其他：
还有一个功能叫“在其他设备上接收电话和短信”，在`app/MdecService`，也会识别 CountryCode, SalesCode 之类的，不在中国大陆不让用，自己改过但改了又配对不了平板。如果您有机会能做这个功能，我愿意测试🫡。
还希望能让应用商店定位到国区，现在有些 app 在应用商店搜不到（例如三星健康、生活助手），apk 有点复杂还没研究怎样实现😂。

**Comment by qlenlen** [comment]
谢谢，非常有帮助的建议。已经将短信与电话的hook功能合并在OneDesign，实测相册定位由Google变为高德，短信也激活了国行特色。

**Comment by BunnyYang05** [comment]
OK，感谢开发者🥰
