### ISSUE TITLE
OneDesign 相册功能相关

### ISSUE THREAD

**Issue by BunnyYang05** [qlenlen/android_kernel_samsung_sm8550#8]
原先全局 hook 的方法会导致 OneDrive 不可用，还会启用百度网盘、微云和美图秀秀服务，将原先的做如下调整下应该能解决：

使以下 5 个类（均为 OneDrive 相关）中`IS_CHINESE_DEVICE`返回 false：
`com.samsung.android.gallery.app.ui.list.timeline.TimelineFragment`
`com.samsung.android.gallery.app.ui.list.timeline.tipcard.OneDrivePromotionTipCard`
`com.samsung.android.gallery.app.ui.list.timeline.tipcard.OneDriveQuotaTipCard`
`com.samsung.android.gallery.settings.delegate.TipCardDelegate`
`com.samsung.android.gallery.settings.provider.SettingSearchIndexablesProvider`

对于 `com.samsung.android.gallery.support.utils.Features`，
使 `IS_CHINESE_DEVICE`, `SUPPORT_ONE_DRIVE_MENU_ON_TOOL_BAR`返回 true
`SUPPORT_MEITU`, `SUPPORT_BAIDU_CLOUD`, `SUPPORT_TENCENT_CLOUD`三个为 false（其实都可以关掉，感觉保留下来也可以）

**Comment by qlenlen** [comment]
由于 `IS_CHINESE_DEVICE` 的判断源头均来自类 `com.samsung.android.gallery.support.utils.Features$96`，因此较难实现针对不同来源的函数调用给出不同的返回值。暂不清楚xposed框架是否支持读取函数上级调用者或对应的上下文。
目前认为要兼顾OneDrive与AMAP，可能需要放弃全局 `IS_CHINESE_DEVICE` 修改，针对细节判断做单独hook，尚需进一步研究。
感谢建议！

**Comment by BunnyYang05** [comment]
反过来修改以下的类可以抛弃全局的修改，但是除了前三个类只涉及简单的布尔值，其他的 `IS_CHINESE_DEVICE` 都来自 `Features$96`，且套在 if 语句中，不知道怎么改：

`com.samsung.android.gallery.app.ui.list.search.pictures.headerview.SearchMapHeaderView`//允许按照位置搜索照片
使 `FEATURE_IS_CHINESE` 为 `true`

`com.samsung.android.gallery.app.ui.map.factory.GalleryMapFactory`//判断使用 AMAP 或 Google Maps
使 `USE_AMAP` 为 `true`

`com.samsung.android.gallery.app.ui.moreinfo.item.MoreInfoLocationBase`//使照片-更多信息页面支持修改定位信息
使 `isEditable` 和 `supportMoveAuthSetting` 为 `true`

`com.samsung.android.gallery.app.ui.dialog.DialogFactory`//隐私协议相关
`com.samsung.android.gallery.app.ui.moreinfo.item.MoreInfoItemFactory`//使照片-更多信息页面正确加载预览地图
`com.samsung.android.gallery.module.map.manager.AddressHelper`//地址显示格式相关
`com.samsung.android.gallery.module.map.manager.AddressHelper$GetAddressListFromKeyword`//地址显示格式相关
`com.samsung.android.gallery.module.map.manager.AddressHelper$GetNormalAddress`//地址显示格式相关
`com.samsung.android.gallery.module.settings.SettingPreference$23`//相册设置添加“CMH Provider”选项
`com.samsung.android.gallery.settings.delegate.DialogDelegate`//隐私协议相关
`com.samsung.android.gallery.settings.delegate.NavigatorDelegate`//隐私协议相关

另外，`com.samsung.android.gallery.settings.ui.SettingFragment` 里有两处引用了来自`com.samsung.android.gallery.settings.ui.BasePresenter` 的布尔值 `isChineseDevice`（该值完全由 `IS_CHINESE_DEVICE` 决定）。一处在 `loadCloudSyncPreference` 方法里，若是中国设备则移除设置里的同步选项；而另一处在 `lambda$loadAdvancedPreference$49` 方法里，负责往相册设置里添加“显示地点名称”选项。不清楚是否可以实现只 hook 后者。

**Comment by BunnyYang05** [comment]
我的相册好像本身就不支持OneDrive同步……模块作用域不选相册，清除数据，还是没有同步选项😭（用的自制港版官改，改了csc里一些运营商信息，可能有影响）
同步可能还需要港区账号，SIM 卡也有限制

**Comment by qlenlen** [comment]
₍₍Ϡ(੭•̀ω•́)੭✧⃛ 太详细了，赞！
空下来会一点点的整合进模块，希望可以兼顾到高德与OneDrive😁

**Comment by BunnyYang05** [comment]
好的好的🥳
还有一个小问题，不开新issue了：已经安装了黄页APP，但是港版定制里的"显示黄页"是灰色不可选

**Comment by qlenlen** [comment]
> 好的好的🥳
> 还有一个小问题，不开新issue了：已经安装了黄页APP，但是港版定制里的"显示黄页"是灰色不可选

黄页功能还没完善好，测试下来未正确显示

**Comment by BunnyYang05** [comment]
> > 好的好的🥳
> > 还有一个小问题，不开新issue了：已经安装了黄页APP，但是港版定制里的"显示黄页"是灰色不可选
> 
> 黄页功能还没完善好，测试下来未正确显示

OneDesign 作用域都没选 Dialer，装了国行系统的版本之后黄页直接就显示了😳

**Comment by qlenlen** [comment]
> > > 好的好的🥳
> > > 还有一个小问题，不开新issue了：已经安装了黄页APP，但是港版定制里的"显示黄页"是灰色不可选
> > 
> > 黄页功能还没完善好，测试下来未正确显示
> 
> OneDesign 作用域都没选 Dialer，装了国行系统的版本之后黄页直接就显示了😳

这么说的话，国行与港版的电话app本体居然是有差异的吗

**Comment by BunnyYang05** [comment]
> > > > 好的好的🥳
> > > > 还有一个小问题，不开新issue了：已经安装了黄页APP，但是港版定制里的"显示黄页"是灰色不可选
> > > 
> > > 
> > > 黄页功能还没完善好，测试下来未正确显示
> > 
> > 
> > OneDesign 作用域都没选 Dialer，装了国行系统的版本之后黄页直接就显示了😳
> 
> 这么说的话，国行与港版的电话app本体居然是有差异的吗

好像是，反混淆之后看，国行的res里多了yp开头的几个文件，应该就是yellowpage，dex里也有区别但是好像加密了看不出
